### ISSUE TITLE
alpine to reduce the size?

### ISSUE THREAD

**Issue by cordoval** [jsreportonline/phantom-pdf#1]
for clusters and good use of resources

it would be ideal to have this container reduced from more than 1GB to at least some hundred MB.

Is this a possibility? I am currently using this service but in https as well.

**Comment by pofider** [comment]
Running phantomjs on alpine is hard. I tried it at the beginning but failed. 

Currently we rotate only limited number of phantomjs containers in jsreportonline and the disk space is cheap so we are not willing to invest more time into it.

Please let us know if you find a way how to run this on Alpine, we would happily use your solution.

**Comment by cordoval** [comment]
what things did you try or where did you get stuck on alpine with phantom

i come from the trouble of wkthmltopdf on alpine and i came here because it seems it is better suited

**Comment by pofider** [comment]
I'm not sure, it is quiet some time ago. You see yourself that the installation is very complex
https://github.com/Overbryd/docker-phantomjs-alpine/blob/master/Dockerfile

and we still need bunch of fonts to install, I have no clue how it would work without apt-get.
https://github.com/jsreportonline/phantom-pdf/blob/master/Dockerfile#L8

It gets really complex and as I mentioned it was not the highest priority for us to decrease the size.
