### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by cordoval** [jsreportonline/phantom-pdf#2]
```
docker run -p 4000:4000 -e "CRT=" -e "KEY=" vendor/printing
curl -k -H "Content-Type: application/json" -X POST -d '{ "html": "<h1>Hello world</h1>"}' https://printing-service:4000
```

**Comment by pofider** [comment]
Thank you for your example.
I see you use this docker image as the pdf converter service. 
However the purpose of this image is only to sandbox the pdf conversion used by jsreportonline service. I understand it can be used right now in standalone way, but I'm not sure if we won't diverge in time too much. Right now it seems to me that it should be better idea to create your own image.

Maybe it would be great if we would maintain all of our jsreportonline "rendering" containers in standalone way. Need to think about it, but I'm afraid that jsreportonline requirements can still be quite different in time.

**Comment by cordoval** [comment]
when you say diverge in time too much what do you mean?

**Comment by pofider** [comment]
I mean that by now it is usable in the standalone way. However we mind need some features for jsreportonline to be present in the image and such changes could break the meaningful standalone usage.

**Comment by pofider** [comment]
The requirements for both scenarios can be divergent.

**Comment by cordoval** [comment]
i don't mind if it does so, it should be simple to adapt. And probably will seldom happen, but it is ok np.

**Comment by pofider** [comment]
Yes, true. 

I probably mainly don't want to mislead developers that this image is designed for public by giving there readme and instructions. Interesting you've even found it. :)

However as I said the idea of offering our jsreportonline images for the standalone public use is very interesting. We will think about that. It mainly needs some time to shape them up and provide instructions, but it could work.
